---
- name: Nix | Install xxh | command
  community.general.pipx:
    name: xxh-xxh
    executable: "{{ pipx_exe }}"

- name: Nix | Install xxh powerlevel10k plugin | command
  command:
    cmd: "{{ bin_directory }}/xxh +I xxh-plugin-zsh-powerlevel10k"
  args:
    creates: "{{ xxh_plugin_dir }}/xxh-plugin-zsh-powerlevel10k"
